// Mocks generated by Mockito 5.4.6 from annotations
// in factoscope/test/cours_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:factoscope/models/cours.dart' as _i5;
import 'package:factoscope/repositories/cours_repository.dart' as _i4;
import 'package:factoscope/ui/api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCoursComplet_0 extends _i1.SmartFake implements _i2.CoursComplet {
  _FakeCoursComplet_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i2.CoursDistant>> getCoursDisponibles() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCoursDisponibles,
          [],
        ),
        returnValue:
            _i3.Future<List<_i2.CoursDistant>>.value(<_i2.CoursDistant>[]),
      ) as _i3.Future<List<_i2.CoursDistant>>);

  @override
  _i3.Future<List<_i2.ModuleDistant>> getModulesDisponibles() =>
      (super.noSuchMethod(
        Invocation.method(
          #getModulesDisponibles,
          [],
        ),
        returnValue:
            _i3.Future<List<_i2.ModuleDistant>>.value(<_i2.ModuleDistant>[]),
      ) as _i3.Future<List<_i2.ModuleDistant>>);

  @override
  _i3.Future<List<_i2.CoursDistant>> getCoursDistantsDuModule(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCoursDistantsDuModule,
          [moduleId],
        ),
        returnValue:
            _i3.Future<List<_i2.CoursDistant>>.value(<_i2.CoursDistant>[]),
      ) as _i3.Future<List<_i2.CoursDistant>>);

  @override
  _i3.Future<_i2.CoursComplet> getCoursComplet(int? coursId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCoursComplet,
          [coursId],
        ),
        returnValue: _i3.Future<_i2.CoursComplet>.value(_FakeCoursComplet_0(
          this,
          Invocation.method(
            #getCoursComplet,
            [coursId],
          ),
        )),
      ) as _i3.Future<_i2.CoursComplet>);

  @override
  _i3.Future<List<_i2.QcmDistant>> getQcmDuCours(int? coursId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQcmDuCours,
          [coursId],
        ),
        returnValue: _i3.Future<List<_i2.QcmDistant>>.value(<_i2.QcmDistant>[]),
      ) as _i3.Future<List<_i2.QcmDistant>>);

  @override
  _i3.Future<List<_i2.ClozeDistant>> getClozesDuCours(int? coursId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClozesDuCours,
          [coursId],
        ),
        returnValue:
            _i3.Future<List<_i2.ClozeDistant>>.value(<_i2.ClozeDistant>[]),
      ) as _i3.Future<List<_i2.ClozeDistant>>);

  @override
  _i3.Future<bool> testConnection() => (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [CoursRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoursRepository extends _i1.Mock implements _i4.CoursRepository {
  MockCoursRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> create(_i5.Cours? cours) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [cours],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> createOrUpdate(_i5.Cours? cours) => (super.noSuchMethod(
        Invocation.method(
          #createOrUpdate,
          [cours],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i5.Cours>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Cours>>.value(<_i5.Cours>[]),
      ) as _i3.Future<List<_i5.Cours>>);

  @override
  _i3.Future<_i5.Cours?> getById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i3.Future<_i5.Cours?>.value(),
      ) as _i3.Future<_i5.Cours?>);

  @override
  _i3.Future<int> update(_i5.Cours? cours) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [cours],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> delete(int? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i5.Cours>> getCoursesByModuleId(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCoursesByModuleId,
          [moduleId],
        ),
        returnValue: _i3.Future<List<_i5.Cours>>.value(<_i5.Cours>[]),
      ) as _i3.Future<List<_i5.Cours>>);

  @override
  _i3.Future<int> markAsDownloaded(int? coursId) => (super.noSuchMethod(
        Invocation.method(
          #markAsDownloaded,
          [coursId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
